<nav>
    <ul>
        <li><a href="/admin">Home</a></li>
        <li><a href="/createUser">Create user</a></li>
        <li ><a id="logoutBtn" href="/logout">Logout</a></li>
    </ul>
</nav>

<style>
    nav {
        background-color: #f1f1f1;
        padding: 10px;
    }

    nav ul {
        list-style-type: none;
        padding: 0;
    }

    nav ul li {
        display: inline;
    }

    nav ul li a {
        color: black;
        text-decoration: none;
        padding: 1rem;
        border: 1px solid #ccc;
        display: inline-block;
    }

    nav ul li a:hover {
        background-color: #555;
        color: white;
    }

    nav ul li a#logoutBtn {
        float: right;
    }
</style>