<nav>
    <ul>
        <?php

            require_once './sessionEditor.php';

            $isAdmin = SessionEditor::getObject(SessionEditor::USER)->is_admin;

            if($isAdmin)
            {
                echo '<li><a href="/admin">Admin</a></li>';
                echo '<li><a href="/createUser">Create User</a></li>';
            }
            else
            {
                echo '<li><a href="/home">Home</a></li>';
                echo '<li><a href="/submitRequest">Submit Request</a></li>';
            }
        ?>
        <li ><a id="logoutBtn" href="/logout">Logout</a></li>
    </ul>
</nav>

<style>
    nav {
        background-color: #f1f1f1;
        padding: 1rem;
    }

    nav ul {
        list-style-type: none;
        padding: 0;
    }

    nav ul li {
        display: inline;
    }

    nav ul li a {
        color: black;
        text-decoration: none;
        padding: 1rem;
        border: 1px solid #ccc;
        display: inline-block;
    }

    nav ul li a:hover {
        background-color: #555;
        color: white;
    }

    nav ul li a#logoutBtn {
        float: right;
    }
</style>