<?php
    include_once "sessionEditor.php"; 
    include_once "./models/userModel.php";


    $selectedUser = ($data['selectedUser']) ?? null;

    $userType = $selectedUser->is_admin ?? 0;

    /* Dont render rest of the page if 
    user id does not exist and we are in the
    update user page*/
    if(!$selectedUser && $requestURL === "/updateUser")
    {
        return;
    }
?>


<form action="<?php echo $requestURL?>" method="POST">
    <label for="firstName" >First name</label>
    <input type="text" value="<?php echo $selectedUser->first_name ?? null ?>" name="firstName" placeholder="first name">
    <label for="lastName">Last name</label>
    <input type="text" value="<?php echo $selectedUser->last_name ?? null ?>" name="lastName" placeholder="last name">
    <label for="email">Email</label>
    <input type="text" value="<?php echo $selectedUser->email ?? null ?>" name="email" placeholder="email">

    <?php

    if($requestURL !== "/updateUser")
    {

        echo '
        <label for="password">Password</label>
        <input type="password" name="password" placeholder="password">
        <label for="confirmPassword">Confirm Password</label>
        <input type="password" name="confirmPassword" placeholder="password">
        ' ;
    }
    else
    {
        if(isset($_GET['id']))
        {
            $id = $_GET['id'];
            echo '<input type="hidden" name="id" value="'.$id.'">';
        }
    }

    ?>

    <label for="userType">User type</label>

    
    <select name="userType">
        <option value="0" <?php if($userType == 0) echo 'selected'?>>User</option>
        <option value="1" <?php if($userType == 1) echo 'selected'?>>Admin</option>
    </select>

    <input type="submit" value="<?php echo $submitValue;?>">
</form>