<head>
    <title>Admin panel</title>
</head>

<?php include_once "views/layouts/navBar.phtml"; ?>

<body>
    <?php

    $users = ($data['users']);

    echo "<div class='user-container'>";

    foreach ($users as $user) 
    {
        $userType = $user->is_admin ? 'admin' : 'employee';

        echo "<div class='user'>";
        echo $user->first_name . ' ' . $user->last_name . ' ' . $user->email . ' ' . $userType;
        echo "<button onclick='updateUser($user->id)'>Update</button>";
        echo "</div>";
    }

    echo "</div>";

    ?>
    
    <script>
        function updateUser(id)
        {
            window.location.href = "/updateUser?id=" + id;
        }
    </script>

    <style>
        #create-user-btn 
        {
            float: right;
        }

        .user-container 
        {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            margin-bottom: 10px;
        }

        .user
        {
            padding-top: 2rem;
        }

    </style>

</body>