<head>
    <title>Home</title>
</head>

<?php
    include_once "views/layouts/navBar.phtml";
?>

<?php

require_once './models/submissionModel.php';

$submissions = ($data['submissions']);

?>

<?php require_once './views/layouts/alerts.phtml'; ?>

<body>
    <div class="submissions">
        <h1>Submissions</h1>
        
        <?php
        foreach($submissions as $submission)
        {

            echo "<div class='submission'>";
            echo "<p>Submitted: " . $submission->dateSubmitted . "</p>";
            echo "<p>Dates requested: " . $submission->vacationStart . " until " . $submission->vacationEnd . "</p>";
            echo "<p>Days requested: " . $submission->getDaysRequested() . "</p>";
            echo "<div class='reason'> <p>Reason: </p>" . $submission->reason . "</div>";
            echo "<p>Status: " . $submission->status . "</p>";
            echo "</div>";
        }
        ?>
    </div>
</body>

<style>
    .submissions 
    {
        display: flex;
        flex-direction: column;
        flex-wrap: wrap;
        justify-content: space-around;
        align-items: center;
        margin: 0 auto;
        width: 80%;
    }

    .submission 
    {
        border: 1px solid black;
        padding: 1rem;
        margin: 1rem;
        width: 30%;
    }
    
    .reason
    {
        border: 1px solid black;
        padding: 1rem; 
    }
</style>