<head>
    <title>login</title>
</head>

<body>
    <h1>Login</h1>

    <?php
    include_once "views/layouts/alerts.phtml";
    ?>

    <form action="/userLogin" method="POST">
        <label for="username">email</label>
        <input type="text" name="email" placeholder="email">
        <label for="password">Password</label>
        <input type="password" name="password" placeholder="password">
        <input type="submit" value="login">
    </form>
</body>
