<head>
    <title>Submit request</title>
</head>

<?php
    include_once "views/layouts/navBar.phtml";
?>

<body>
    <?php
    include_once "views/layouts/alerts.phtml";
    ?>
    <div class="container">
        <h1>Submit request</h1>
        <form action="/submitRequest" method="post">
            <div class="form-group">
                <label for="startDate">Date from</label>
                <input type="date" class="form-control" id="startDate" name="startDate" required>
            </div>
            <div class="form-group">
                <label for="endDate">Date to</label>
                <input type="date" class="form-control" id="endDate" name="endDate" required>
            </div>
            <div class="form-group">
                <label for="reason">Reason</label>
                <textarea class="form-control" id="reason" name="reason" rows="3" required></textarea>
            </div>
            <button class="form-group" type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</body>

<style>
    .form-group
    {
        margin-bottom: 1rem;
    }

    .container
    {
        display: flex;
        flex-direction: column;
        flex-wrap: wrap;
        justify-content: space-around;
        align-items: center;
        
    }

</style>